# Use Ubuntu 14.04
dist: trusty

sudo: false

language: ruby

rvm: 2.2.3

cache:
  - apt
  - bundler
  - directories:
    - $HOME/.ivy2/cache

jdk:
  - openjdk7

install:
  - gem install nanoc:4.0.2
  - gem install redcarpet
  - gem install nokogiri

addons:
  apt:
    sources:
      - sourceline: 'deb https://dl.bintray.com/sbt/debian /'
        key_url: 'https://bintray.com/user/downloadSubjectPublicKey?username=sbt'
    packages:
      - sbt=0.13.16
      - pandoc
      - latex-cjk-all
      - texlive-full

before_script:
 - export JVM_OPTS="-Dfile.encoding=UTF-8 -Xmx1G -Xms1G -server -XX:ReservedCodeCacheSize=128M -XX:MaxPermSize=512M"

script:
  - sbt makeSite

after_success:
  - .travis/publish-site.sh

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/ghpages
    - $HOME/.sbt/boot
