# Use Ubuntu 14.04
dist: trusty

sudo: false

language: ruby

rvm: 2.2.3

cache:
  - apt
  - bundler
  - directories:
    - $HOME/.ivy2/cache

jdk:
  - oraclejdk8

install:
  - gem install nanoc:4.0.2
  - gem install redcarpet
  - gem install nokogiri

addons:
  apt:
    packages:
      - pandoc
      - latex-cjk-all
      - texlive-full

before_script:
 - export JVM_OPTS="-Dfile.encoding=UTF-8 -Xmx1G -Xms1G -server -XX:ReservedCodeCacheSize=128M -XX:MaxPermSize=512M"

script:
  - wget https://raw.githubusercontent.com/paulp/sbt-extras/7e0418fa6520623f17941061f3ab07f7b2ef4f8f/sbt && chmod +x sbt
  - ./sbt makeSite
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

after_success:
  - .travis/publish-site.sh

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/ghpages
    - $HOME/.sbt/boot

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete
