# Use Ubuntu 14.04
dist: trusty

sudo: false

language: ruby

rvm: 2.2.3

cache:
  - apt
  - bundler
  - directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

jdk: oraclejdk8

install:
  - gem install nanoc:4.0.2
  - gem install redcarpet
  - gem install nokogiri

addons:
  apt:
    sources:
      - sourceline: 'deb https://dl.bintray.com/sbt/debian /'
      - key_url: 'https://bintray.com/user/downloadSubjectPublicKey?username=sbt'
    packages:
      - sbt=1.1.2
      - pandoc
      - latex-cjk-all
      - texlive-full

before_script:
 - export JVM_OPTS="-Dfile.encoding=UTF-8 -Xmx1G -Xms1G -server -XX:ReservedCodeCacheSize=128M"

# Use `/usr/bin/sbt` that we manually installed
script: /usr/bin/sbt -Dsbt.website.generate_pdf scalafmtTest scripted makeSite

after_success: .travis/publish-site.sh

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt  -name "*.lock"               -delete
